Enhancement (ci): Change to fully incremental builds
This uses remote image and inline cache for incremental builds.

diff --git a/variants/v4.8.3-docker-rootless-go-1.19.7-alpine-3.15/Dockerfile b/variants/v4.8.3-docker-rootless-go-1.19.7-alpine-3.15/Dockerfile
--- a/variants/v4.8.3-docker-rootless-go-1.19.7-alpine-3.15/Dockerfile
+++ b/variants/v4.8.3-docker-rootless-go-1.19.7-alpine-3.15/Dockerfile
@@ -1,5 +1,83 @@
-ARG BASE_IMAGE
-FROM $BASE_IMAGE
+# syntax=docker/dockerfile:1
+FROM alpine:3.15
+ARG TARGETPLATFORM
+ARG TARGETOS
+ARG TARGETARCH
+ARG TARGETVARIANT
+ARG BUILDPLATFORM
+ARG BUILDOS
+ARG BUILDARCH
+ARG BUILDVARIANT
+RUN set -ex; \
+    echo "TARGETPLATFORM="; \
+    echo "TARGETOS="; \
+    echo "TARGETARCH="; \
+    echo "TARGETVARIANT="; \
+    echo "BUILDPLATFORM="; \
+    echo "BUILDOS="; \
+    echo "BUILDARCH="; \
+    echo "BUILDVARIANT=";
+
+RUN --mount=type=secret,id=GITHUB_TOKEN \
+    DEPS='alpine-sdk bash libstdc++ libc6-compat python3' \
+    && apk add --no-cache $DEPS \
+    # Constraint to npm 8, or else npm will fail with 'npm ERR! python is not a valid npm option'. See: https://stackoverflow.com/questions/74522956/python-is-not-a-valid-npm-option and https://jubianchi.github.io/semver-check/#/~8/8
+    && apk add --no-cache 'npm~8' 'nodejs~16' \
+    && npm config set python python3 \
+    && GITHUB_TOKEN=$( cat /run/secrets/GITHUB_TOKEN ) npm install --global code-server@4.8.3 --unsafe-perm \
+    # Fix missing dependencies. See: https://github.com/coder/code-server/issues/5530
+    && cd /usr/local/lib/node_modules/code-server/lib/vscode && GITHUB_TOKEN=$( cat /run/secrets/GITHUB_TOKEN ) npm install --legacy-peer-deps \
+    && code-server --version \
+    && apk del $DEPS
+
+# Install tools
+RUN apk add --no-cache bash bash-completion ca-certificates curl gnupg git git-lfs iotop jq less lsblk make nano openssh-client openssl p7zip rsync tree yq
+
+RUN apk add --no-cache sudo
+RUN adduser -u 1000 --gecos '' -D user
+RUN echo 'user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/user
+
+# Install common extensions
+USER user
+# beautify - code formatter
+RUN code-server --install-extension hookyqr.beautify@1.4.11
+# docker
+RUN code-server --install-extension ms-azuretools.vscode-docker@1.18.0
+# firefox
+RUN code-server --install-extension firefox-devtools.vscode-firefox-debug@2.9.1
+# git
+RUN code-server --install-extension donjayamanne.githistory@0.6.19
+RUN code-server --install-extension eamodio.gitlens@11.6.0
+# github. Install the latest compatible version
+RUN code-server --install-extension github.vscode-pull-request-github
+# gitlab
+RUN code-server --install-extension gitlab.gitlab-workflow@3.60.0
+# jinja
+RUN code-server --install-extension samuelcolvin.jinjahtml@0.16.0
+RUN code-server --install-extension wholroyd.jinja@0.0.8
+# kubernetes
+RUN code-server --install-extension ms-kubernetes-tools.vscode-kubernetes-tools@1.3.11
+# markdown
+RUN code-server --install-extension bierner.markdown-preview-github-styles@0.1.6
+RUN code-server --install-extension DavidAnson.vscode-markdownlint@0.43.2
+# prettier - code formatter
+RUN code-server --install-extension esbenp.prettier-vscode@9.0.0
+# svg
+RUN code-server --install-extension jock.svg@1.4.17
+# terraform
+RUN code-server --install-extension hashicorp.terraform@2.14.0
+# toml
+RUN code-server --install-extension bungcip.better-toml@0.3.2
+# vscode
+RUN code-server --install-extension vscode-icons-team.vscode-icons@11.13.0
+# xml
+RUN code-server --install-extension redhat.vscode-xml@0.18.0
+# yaml
+RUN code-server --install-extension redhat.vscode-yaml@1.9.1
+
+# Add a default settings.json
+USER user
+COPY --chown=1000:1000 settings.json /home/user/.local/share/code-server/User/settings.json
 
 # Install docker
 # See: https://github.com/moby/moby/blob/v20.10.22/project/PACKAGERS.md
